name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Amazon Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Restore dependencies
      run: dotnet restore src/MyLambdaFunction/MyLambdaFunction.csproj

    - name: Build
      run: dotnet build src/MyLambdaFunction/MyLambdaFunction.csproj --configuration Release

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
      run: |
        dotnet lambda deploy-function MyLambdaFunction \
          --region $AWS_REGION \
          --function-role arn:aws:iam::123456789012:role/YourLambdaExecutionRole
